-- Create the UserRole enum
CREATE TYPE "UserRole" AS ENUM ('student', 'organizer', 'admin');

-- Create the users table
CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "email" VARCHAR(255) UNIQUE NOT NULL,
    "passwordHash" VARCHAR(255) NOT NULL,
    "role" "UserRole" NOT NULL,
    "createdAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create the user_profiles table
CREATE TABLE "user_profiles" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT UNIQUE NOT NULL,
    "bio" VARCHAR(500),
    "createdAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "user_profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create the events table
CREATE TABLE "events" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "start_date" TIMESTAMP(6),
    "end_date" TIMESTAMP(6),
    "user_id" BIGINT NOT NULL,
    "createdAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "events_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- Create the event_attendees table (junction table)
CREATE TABLE "event_attendees" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "event_id" BIGINT NOT NULL,
    "status" VARCHAR(50),
    CONSTRAINT "event_attendees_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "event_attendees_event_id_fkey" FOREIGN KEY ("event_id") REFERENCES "events"("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "event_attendees_user_id_event_id_key" UNIQUE ("user_id", "event_id")
);

-- Indexes for performance
CREATE INDEX "users_email_idx" ON "users"("email");
CREATE INDEX "user_profiles_user_id_idx" ON "user_profiles"("user_id");
CREATE INDEX "events_user_id_idx" ON "events"("user_id");
CREATE INDEX "events_start_date_idx" ON "events"("start_date");
CREATE INDEX "events_end_date_idx" ON "events"("end_date");
CREATE INDEX "event_attendees_user_id_idx" ON "event_attendees"("user_id");
CREATE INDEX "event_attendees_event_id_idx" ON "event_attendees"("event_id");